const $=s=>document.querySelector(s);
const state={index:null,date:null,i:-1,activity:false,musicOn:false,musicIndex:0};
const video=$('#video'), select=$('#dateSelect'), timeline=$('#timeline'), music=$('#music');
const musicPlaylist=[
  {title:'Sleep',artist:'Scott Buckley',url:'https://www.scottbuckley.com.au/library/wp-content/uploads/2019/08/sb_sleep.mp3'},
  {title:'She Moved Mountains',artist:'Scott Buckley',url:'https://www.scottbuckley.com.au/library/wp-content/uploads/2014/07/sb_shemovedmountains.mp3'},
  {title:'There is a Place',artist:'Scott Buckley',url:'https://www.scottbuckley.com.au/library/wp-content/uploads/2019/04/sb_thereisaplace.mp3'}
];
function fmt(sec){sec=Math.max(0,Math.round(sec));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?`${h}h ${m}m ${s}s`:`${m}m ${s}s`}
function fmtTime(iso){return new Date(iso).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})}
function dayItems(){return state.index?.days?.[state.date]||[]}
function renderDays(){const days=Object.keys(state.index?.days||{}).sort();select.innerHTML=days.length?days.map(d=>`<option value="${d}">${new Date(d+'T00:00:00').toLocaleDateString([], {month:'long',day:'numeric',year:'numeric'})}</option>`).join(''):'<option>No footage imported</option>';state.date=new URLSearchParams(location.search).get('date')||days[0]||null;if(state.date&&!state.index.days[state.date])state.date=days[0];if(state.date)select.value=state.date;renderDay()}
function renderDay(){const a=dayItems();state.i=-1;const total=a.reduce((x,y)=>x+(y.duration||0),0);$('#dayStats').textContent=a.length?`${a.length} recordings · ${fmt(total)} footage · ${fmtTime(a[0].startTime)} → ${fmtTime(a[a.length-1].startTime)}`:'No imported footage yet';timeline.innerHTML='';a.forEach((x,i)=>{const d=new Date(x.startTime),start=d.getHours()*3600+d.getMinutes()*60+d.getSeconds(),left=start/86400*100,width=Math.max((x.duration||1)/86400*100,.18);const b=document.createElement('button');b.className='clip';b.style.left=left+'%';b.style.width=width+'%';b.title=`${fmtTime(x.startTime)} · ${fmt(x.duration||0)}`;b.dataset.i=i;b.onclick=()=>load(i,true);timeline.appendChild(b)});renderChapters();$('#videoStatus').textContent=a.length?'Select a recording to begin.':'The library is ready. Waiting for the first migrated MP4.';video.removeAttribute('src');video.load()}
function load(i,play=false){const a=dayItems();if(!a[i])return;state.i=i;document.querySelectorAll('.clip').forEach((e,j)=>e.classList.toggle('active',j===i));video.src=a[i].url;video.load();$('#videoStatus').textContent=`${fmtTime(a[i].startTime)} · ${a[i].name}`;if(play)video.play().catch(()=>{})}
video.addEventListener('ended',()=>{if(state.i<dayItems().length-1)load(state.i+1,true)});
video.addEventListener('volumechange',()=>$('#videoVolume').value=video.volume);$('#videoVolume').oninput=e=>video.volume=+e.target.value;
$('#nextBtn').onclick=()=>state.i>=0&&load(Math.min(state.i+1,dayItems().length-1),true);$('#prevBtn').onclick=()=>state.i>=0&&load(Math.max(state.i-1,0),true);
select.onchange=()=>{if(!state.date)return;state.date=select.value;history.replaceState(null,'','?date='+state.date);renderDay()};
$('#activityBtn').onclick=()=>{state.activity=!state.activity;timeline.classList.toggle('activity',state.activity);$('#activityBtn').textContent=state.activity?'Full 24-hour View':'Zoom to Activity';if(state.activity){const a=dayItems();if(a.length){const starts=a.map(x=>{const d=new Date(x.startTime);return d.getHours()*3600+d.getMinutes()*60+d.getSeconds()}),ends=a.map((x,j)=>starts[j]+(x.duration||1));const lo=Math.max(0,Math.min(...starts)-1800),hi=Math.min(86400,Math.max(...ends)+1800);timeline.querySelectorAll('.clip').forEach((b,j)=>{const x=a[j],d=new Date(x.startTime),s=d.getHours()*3600+d.getMinutes()*60+d.getSeconds();b.style.left=((s-lo)/(hi-lo)*100)+'%';b.style.width=Math.max((x.duration||1)/(hi-lo)*100,.7)+'%'});timeline.dataset.window=`${lo}-${hi}`}}else renderDay()};
$('#timelineBtn').onclick=()=>{const sec=$('#timelineSection'),hidden=sec.style.display==='none';sec.style.display=hidden?'':'none';$('#timelineBtn').textContent=hidden?'Hide Timeline':'Show Timeline'};
$('#fullscreenBtn').onclick=()=>video.requestFullscreen?.();
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();video.paused?video.play():video.pause()}if(e.key==='ArrowLeft')video.currentTime=Math.max(0,video.currentTime-5);if(e.key==='ArrowRight')video.currentTime+=5;if(e.key==='ArrowUp')state.i>=0&&load(Math.max(state.i-1,0),true);if(e.key==='ArrowDown')state.i>=0&&load(Math.min(dayItems().length-1,state.i+1),true);if(e.key.toLowerCase()==='f')$('#fullscreenBtn').click();if(e.key.toLowerCase()==='m')video.muted=!video.muted});
function renderChapters(){const c=$('#chapters');c.innerHTML=dayItems().length?'<p style="color:#888">Chapter controls will appear when chapter metadata is populated.</p>':'<p style="color:#888">Chapters will appear with imported footage.</p>'}
function updateMusicLabel(){const t=musicPlaylist[state.musicIndex];$('#musicTrack').textContent=state.musicOn?`Music: ${t.title} — ${t.artist}`:'Music is off.'}
function playMusicTrack(index){if(!musicPlaylist.length)return;state.musicIndex=(index+musicPlaylist.length)%musicPlaylist.length;const t=musicPlaylist[state.musicIndex];music.src=t.url;music.volume=+$('#musicVolume').value;updateMusicLabel();music.play().catch(()=>{state.musicOn=false;$('#musicBtn').textContent='Music: OFF';updateMusicLabel()})}
function stopMusic(){music.pause();music.removeAttribute('src');music.load();state.musicOn=false;$('#musicBtn').textContent='Music: OFF';updateMusicLabel()}
music.addEventListener('ended',()=>{if(state.musicOn)playMusicTrack(state.musicIndex+1)});
$('#musicVolume').oninput=e=>music.volume=+e.target.value;
$('#musicBtn').onclick=()=>{if(state.musicOn)stopMusic();else{state.musicOn=true;$('#musicBtn').textContent='Music: ON';playMusicTrack(state.musicIndex)}};
updateMusicLabel();
fetch('data/wildlife-index.json').then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(x=>{state.index=x;renderDays()}).catch(e=>{$('#videoStatus').textContent='Unable to load metadata index.';console.error(e)});
